name: Create Release Binaries
on:
  push:
    branches: [ main ]       # Push events to every tag not containing /
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@main
      - name: set tag
        run: git tag --points-at HEAD
      - name: tags
        run: echo {{env.HEAD_TAG}}
      - name: tag2
        run: echo ${{github.tag}}
      - name: set tags
        run: echo "TAGS=(`echo ${{ env.HEAD_TAG }} | tr '\n' ' '`)" >> $GITHUB_ENV
      - name: check arr
        run: echo ${{ env.TAGS[1] }}