name: Create Release Binaries
on:
  push:
    branches: [ main ]
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.set_env.outputs.test }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@main
        with:
          fetch-depth: 2
          ref: 'main'
      - name: featch tags
        run: git fetch --tags
      - name: set tag
        run: echo "TAGS=(`echo $(git tag --points-at) | tr '\n' ' '`)" >> $GITHUB_ENV
      - name: set
        id: set_env
        run:echo "::set-output name=test::${{env.TAGS}}"
  build:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - run: echo ${{needs.prepare.outputs.output}}