name: Create Release Binaries
on:
  push:
    branches: [ main ]
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@main
        with:
          fetch-depth: 2
          ref: 'main'
      - run: git checkout HEAD^
      - name: set tag
        run: echo $(git tag --points-at)
      - name:  tag
        run: echo $(git status)
      - name: tags
        run: echo {{env.HEAD_TAG}}
      - name: tag2
        run: echo ${{github.tag}}
      - name: set tags
        run: echo "TAGS=(`echo ${{ env.HEAD_TAG }} | tr '\n' ' '`)" >> $GITHUB_ENV
      - name: check arr
        run: echo ${{ env.TAGS[1] }}