name: Create Release Binaries
on:
  push:
    branches: [ main ]
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.set_env.outputs.test }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@main
        with:
          fetch-depth: 2
          ref: 'main'
      - name: featch tags
        run: git fetch --tags
      - name: set tag
        run: echo "TAGS=$(git tag --points-at | jq  --raw-input .  | jq --slurp . | jq tostring)" >> $GITHUB_ENV
      - name: print var
        run: echo ${{env.TAGS}}
      - name: set
        id: set_env
        run: echo "::set-output name=test::${{env.TAGS}}"
  build:
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix:
        tag: ${{fromJSON(needs.prepare.outputs.output)}}
    steps:
      - name: test
        run: echo ${{matrix.tag}}