name: Create Release Binaries
on:
  push:
    branches: [ main ]
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@main
        with:
          fetch-depth: 2
          ref: 'main'
      - name: featch tags
        run: git fetch --tags
      - name: set tag
        run:  echo "TAGS=(`echo $(git tag --points-at) | tr '\n' ' '`)" >> $GITHUB_ENV
      - name: 'test'
        run: echo ${{ {env.TAGS[1]} }}