name: Create Release Binaries
on:
  push:
    branches: [ main ]       # Push events to every tag not containing /
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: set tags
        run: echo "TAGS=(`echo $(git tag --points-at HEAD) | tr '\n' ' '`)" >> $GITHUB_ENV
      - name: tags
        run: echo $(git tag --points-at HEAD)
      - name: check arr
        run: echo ${{ env.TAGS[1] }}