name: unit-tests

on:
  - push
  - pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      npm_config_user: "root"
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v3
      - name: "nodejs install"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: install yarn
        run: npm install --global yarn
      - name: 'ls'
        run: ls
      - name: "setup"
        run: yarn setup
      - name: "run tests"
        run: yarn test:unit
