name: unit-tests

on:
  - push
  - pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v3
      - name: "nodejs install"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: "dependency install"
        run: yarn setup
      - name: build
        run: yarn lerna run build
      - name: "run tests"
        run: yarn test:unit
